### ISSUE TITLE
No columns renderd in html

### ISSUE THREAD

**Issue by schorsch8878** [buepro/typo3-pp_gridelements#1]
I use pp gridelements 1.1.0 with bootstrappackage 9.1.3 in a 9.5.31 TYPO3. It is a great ext. The Problem: In html i have no columns (col-md-xx). What can be wrong? Many thanks.

**Comment by buepro** [comment]
This would need to be checked in deatail. Please [contact me](mailto:info@buechler.pro) if you are interested on comercial support.
As an alternative the extension [container_elements](https://github.com/buepro/typo3-container_elements) could be used. It provides similar functionality using [container](https://github.com/b13/container).
